package com.project;

/**
 *
 * @author Mohammed Zaid
 */
public class AddUsersPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddUsersPanel
     */
    public AddUsersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel userNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel passwordLabel = new javax.swing.JLabel();
        javax.swing.JLabel emailAddressLabel = new javax.swing.JLabel();
        createUserButton = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        emailAddressField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        adminCheckBox = new javax.swing.JCheckBox();
        phoneNumberField = new javax.swing.JTextField();
        javax.swing.JLabel phoneNumberLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        insertButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();

        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameLabel.setText("User Name:");

        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password:");

        emailAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailAddressLabel.setText("Email Address:");

        createUserButton.setText("Create the User");
        createUserButton.setToolTipText("enter the values in the field first");

        userNameField.setToolTipText("enter the username here");

        emailAddressField.setToolTipText("enter the email address here, Note that this email will be used to reset the password if you have forgot it.");

        passwordField.setToolTipText("enter the password here");

        adminCheckBox.setText("Admin");
        adminCheckBox.setToolTipText("the admin account will be able to create other accounts.");

        phoneNumberField.setToolTipText("enter the phone number");

        phoneNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneNumberLabel.setText("Phone Number:");

        searchButton.setText("Search");

        insertButton.setText("Insert");

        logOutButton.setText("Logout");

        changePasswordButton.setText("Change Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminCheckBox)
                        .addGap(18, 274, Short.MAX_VALUE)
                        .addComponent(createUserButton)
                        .addGap(0, 295, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNameField)
                            .addComponent(emailAddressField)
                            .addComponent(passwordField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePasswordButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(insertButton)
                    .addComponent(logOutButton)
                    .addComponent(changePasswordButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressLabel)
                    .addComponent(emailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserButton)
                    .addComponent(adminCheckBox))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return if the user has checked the adminCheckBox
     */
    public boolean adminAccount(){
        return this.adminCheckBox.isSelected();
    }
    
    /**
     * 
     * @return User Name that the user entered
     */
    public String getUserName(){
        return this.userNameField.getText();
    }
    
    /**
     * 
     * @return Password that the user entered
     */
    public char[] getPassword(){
        return this.passwordField.getPassword();
    }
    
    /**
     * 
     * @return Email Address that the user entered
     */
    public String getEmailAddress(){
        return this.emailAddressField.getText();
    }
    
    /**
     * 
     * @return Phone Number that the user entered
     */
    public String getPhoneNumber(){
        return this.phoneNumberField.getText();
    }

    public void clearFields(){
        this.adminCheckBox.setSelected(false);
        this.emailAddressField.setText("");
        this.passwordField.setText("");
        this.phoneNumberField.setText("");
        this.userNameField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    protected javax.swing.JButton changePasswordButton;
    protected javax.swing.JButton createUserButton;
    private javax.swing.JTextField emailAddressField;
    protected javax.swing.JButton insertButton;
    protected javax.swing.JButton logOutButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneNumberField;
    protected javax.swing.JButton searchButton;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
