package com.project;

/**
 *
 * @author Mohammed Zaid
 */
public class InsertDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataPanel
     */
    public InsertDataPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        javax.swing.JLabel personNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel companyNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel addressLabel = new javax.swing.JLabel();
        javax.swing.JLabel emailAddressLabel = new javax.swing.JLabel();
        javax.swing.JLabel phoneNumberLabel = new javax.swing.JLabel();
        javax.swing.JLabel mobileNumberLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        emailAddressField = new javax.swing.JTextField();
        personNameField = new javax.swing.JTextField();
        companyNameField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        mobileNumberField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        addUsersButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();

        personNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personNameLabel.setText("Person Name:");

        companyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyNameLabel.setText("Company Name:");

        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("Address:");

        emailAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailAddressLabel.setText("Email Address:");

        phoneNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneNumberLabel.setText("Phone Number:");

        mobileNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobileNumberLabel.setText("Mobile Number:");

        saveButton.setText("Save the Data");
        saveButton.setToolTipText("save the data on to the server");

        emailAddressField.setToolTipText("enter the email address of the customer");

        personNameField.setToolTipText("enter the name of the customer.");

        companyNameField.setToolTipText("enter the company name of the customer.");

        phoneNumberField.setToolTipText("enter the phone number of the customer.");

        addressField.setToolTipText("enter the address of the customer.");

        mobileNumberField.setToolTipText("enter the mobile number of the customer.");

        searchButton.setText("Search");

        logOutButton.setText("Logout");

        addUsersButton.setText("Add Users");

        changePasswordButton.setText("Change Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(personNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(companyNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(companyNameField)
                                .addComponent(personNameField)
                                .addComponent(addressField))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mobileNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mobileNumberField)
                                .addComponent(emailAddressField)
                                .addComponent(phoneNumberField)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(saveButton)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(logOutButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                            .addComponent(addUsersButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                            .addComponent(searchButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                            .addComponent(changePasswordButton)))
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchButton)
                        .addComponent(logOutButton)
                        .addComponent(addUsersButton)
                        .addComponent(changePasswordButton))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(personNameLabel)
                        .addComponent(emailAddressLabel)
                        .addComponent(emailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(personNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(companyNameLabel)
                        .addComponent(phoneNumberLabel)
                        .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addressLabel)
                        .addComponent(mobileNumberLabel)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mobileNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(saveButton)
                    .addContainerGap())
        );
    }// </editor-fold>


    public String getPersonName(){
        return this.personNameField.getText();
    }
    
    public String getCompanyName(){
        return this.companyNameField.getText();
    }
    
    public String getAddress(){
        return this.addressField.getText();
    }
    
    public String getEmailAddress(){
        return this.emailAddressField.getText();
    }
    
    public String getPhoneNumber(){
        return this.phoneNumberField.getText();
    }
    
    public String getMobileNumber(){
        return this.mobileNumberField.getText();
    }

    public void clearFields(){
        this.personNameField.setText("");
        this.companyNameField.setText("");
        this.addressField.setText("");
        this.emailAddressField.setText("");
        this.phoneNumberField.setText("");
        this.mobileNumberField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton logOutButton;
    protected javax.swing.JButton addUsersButton;
    private javax.swing.JTextField addressField;
    protected javax.swing.JButton changePasswordButton;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JTextField emailAddressField;
    private javax.swing.JTextField mobileNumberField;
    private javax.swing.JTextField personNameField;
    private javax.swing.JTextField phoneNumberField;
    protected javax.swing.JButton saveButton;
    protected javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
